name: nohealani
favicon: null
layout_spectrum: 0.36429308145307004
typography_spectrum: 0.3820317753124982
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.9035660242661834
  lightness: 0.3721776148304343
  saturation: 0.6021299052517861
  rhythmicContrast: 0.45356262288987637
purpose: []
